# Generated by Django 2.2 on 2019-12-15 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название комнаты')),
                ('chair_cnt', models.PositiveSmallIntegerField(default=0, verbose_name='Количество кресел')),
                ('projector', models.BooleanField(default=False, verbose_name='Наличие проектора')),
                ('marker_board', models.BooleanField(default=False, verbose_name='Наличие маркерной доски')),
                ('description', models.TextField(verbose_name='Описание комнаты')),
            ],
        ),
        migrations.CreateModel(
            name='ReservedMeetingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название мероприятия')),
                ('start_meeting_time', models.DateTimeField(verbose_name='Время начала встречи')),
                ('end_meeting_time', models.DateTimeField(verbose_name='Время окончания встречи')),
                ('confirmed', models.PositiveSmallIntegerField(choices=[(0, 'Отклонена'), (1, 'На модерации'), (2, 'Подтверждена')], default=1, verbose_name='Подтверждение резервирования')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings_time', to='meeting_room_reservation.MeetingRoom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
